USER_LIBS= \
	$(MYPJ)/bin.ss/_$(TARGET).O/libSmart.analysis.a \
	$(MYPJ)/bin.ss/_$(TARGET).O/libSmart.description.a \
	$(MYPJ)/bin.ss/_$(TARGET).O/libSmart.core.a \
	$(SDPPJ)/official.ss/_$(TARGET).O/libNemesis.app.a \
	$(SDPPJ)/official.ss/_$(TARGET).O/libNemesis.xml.a \
	$(SDPPJ)/official.ss/_$(TARGET).O/libNemesis.io.a \
	$(SDPPJ)/official.ss/_$(TARGET).O/libNemesis.core.a 
