USER_LIBS= \
	$(MYPJ)/_$(TARGET).O/libCommon.a \
	$(SDPPJ)/official.ss/_$(TARGET).O/libNemesis.app.a \
	$(SDPPJ)/official.ss/_$(TARGET).O/libNemesis.xml.a \
	$(SDPPJ)/official.ss/_$(TARGET).O/libNemesis.io.a \
	$(SDPPJ)/official.ss/_$(TARGET).O/libNemesis.core.a 

INCLUDE_LMK=$(MAKEFILES_DIR)/empty_include
