USER_LIBS= \
	$(MYPJ)/bin.ss/_$(TARGET).O/libSmart.structure.a \
	$(MYPJ)/bin.ss/_$(TARGET).O/libSmart.core.a \
	$(SDPPJ)/official.ss/_$(TARGET).O/libNemesis.app.a \
	$(SDPPJ)/official.ss/_$(TARGET).O/libNemesis.io.a \
	$(SDPPJ)/official.ss/_$(TARGET).O/libNemesis.core.a

